external_reference.settings:
  type: config_object
  label: 'External Reference settings'
  mapping:
    external_reference_track:
      type: sequence
      label: 'Configuration for each content_type'
      sequence:
        type: mapping
        mapping:
          endpoint_list:
            type: string
            label: 'Endpoint url to retrieve all the contents'
          endpoint_individual:
            type: string
            label: 'Endpoint url to retrive one content'
